### ISSUE TITLE
Change enzymeList.json to a js file

### ISSUE THREAD

**Issue by RavensburgOP** [TeselaGen/ve-sequence-utils#3]
I have the ve-sequence-utils as a dependency in an Angular project with Angular CLI. The enzymeList.json becomes problematic, since the default webpack settings in Angular CLI cannot resolve json files, by changing the enzymeList to a json object in a js file this could be resolved.

**Suggested change**
enzymeList.json -> enzymeList.js

add `module.exports = ` to the beginning of the file

**Comment by tnrich** [comment]
Hey @RavensburgOP sorry for the delay in getting back to you! I just made a new issue template that mentions me (@tnrich) directly so I should get email notifications in the future. 

Hmmm so I have a couple hesitations about doing this change @RavensburgOP because it might be a little heavier to parse a big JS file rather than a big JSON file for most programs. 

Let me CC @tgreen7 because we had been talking about trying to come up with a plan to have a minified & uglified version of the enzyme list already.

We could also try it out as a JS file for a little bit and see if performance is affected anywhere and what our output bundle size looks like.

**Comment by innayarantseva** [comment]
Hey @tnrich! I have the same problem with Webpack compiler here. The trick which @RavensburgOP have mentioned above worked just fine.
Looking forward to hearing from you if you're planning to solve the issue :)

**Comment by tnrich** [comment]
@RavensburgOP and @innayarantseva I've recently published v3.3.1 which has the enzymeList as a .js file instead of a .json file. Hopefully this fixes your issue. Let me know if you have any more issues :)
